### ISSUE TITLE
Add Second Interesting Crime Graph

### ISSUE THREAD

**Issue by asedarski** [Code4HR/explore#10]
Add second graph to the crime section with intelligent data to draw unique conclusions

**Comment by asedarski** [comment]
Number of crimes by hours of day

**Comment by hop-along-polly** [comment]
'Theft' => 154,
  'Assault' => 31,
  'Property Crime' => 42,
  'Robbery' => 15,
  'Assault with Deadly Weapon' => 1,
  'Theft of Vehicle' => 13,
  'Breaking and Entering' => 17,

**Comment by hop-along-polly** [comment]
The data source did not provide timestamps so we chose to break this down as crime by types.
