### ISSUE TITLE
Is this repo functional?

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/explore#2]
can someone update the readme in this repo to mention the current functional status, what it does do (if anything). I can't tell if it's got the JS to talk to the API or if it's just a UI theme for how we want it to look once functional. thanks.

**Comment by asedarski** [comment]
@BretFisher: We will be working on this repo this Sunday and after our progress we will update the readme with the current status of the repo. As of right now, I believe it is just a bootstrap CSS framework that Brandon put together for us

**Comment by asedarski** [comment]
@BretFisher: The repo is technically functional, though it displays dummy data for the graphs and we do not have all of the text we want to display either. We have a lot of connecting yet to do and we still need to create the second page to contain the map. The readme should contain some details of what the current status of the repo is. We will continue to update the readme as we make changes.
