### ISSUE TITLE
use $API_URL for pointing to hercules API

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/explore#26]
I've added a line to the Dockerfile for API_URL, which defaults to http://hercules.code4hr.org. This task will be complete when someone puts this into php, either as a php global or or when it's at least used in an example so we have it documented. We should not hard code URL's in the php or javascript of explore, so lets be sure to put any other URL's or keys needed into the dockerfile as ENV please :)

https://github.com/Code4HR/explore/blob/master/Dockerfile

**Comment by krishnaramya** [comment]
I have placed global variable in PHP.

**Comment by krishnaramya** [comment]
https://github.com/Code4HR/hercules/pull/30

**Comment by BretFisher** [comment]
@krishnaramya I'm confused. The Dockerfile will set $API_URL so that explore knows how to find Hercules in any environment it's running. I would expect then for this issue to be resolved, for explore's config to have a line somewhere like:

`$ApiUrl = getenv('API_URL');`

And then use that for API requests from explore to hercules.

Does that sound right?

**Comment by krishnaramya** [comment]
that's correct.
